# Configuración del modelo RandomForestClassifier (model_pycaret).
# Define parámetros por defecto, espacio de búsqueda para optimización,
# validación cruzada y métricas de evaluación.

name: RandomForestClassifier  # Nombre del modelo usado en el pipeline.

params:  # Parámetros por defecto del modelo.
  n_estimators: 100  # Número de árboles.
  max_depth: null  # Profundidad máxima.
  min_samples_split: 2  # Mínimo de muestras para dividir un nodo.
  min_samples_leaf: 1  # Mínimo de muestras por hoja.
  max_features: "sqrt"  # Número de características a considerar.
  class_weight: null  # Pondera clases según frecuencia.
  random_state: 438  # Semilla para reproducibilidad.
  n_jobs: -1  # Usar todos los procesadores disponibles.
  bootstrap: true  # Usar muestreo con reemplazo.
  criterion: "gini"  # Criterio para la división.
  min_impurity_decrease: 0.0  # Umbral para la reducción de impureza.
  oob_score: false  # No usar puntaje fuera de bolsa.
  verbose: 0  # Sin salida detallada.
  warm_start: false  # No reutilizar soluciones previas.

search_space:  # Espacio de búsqueda para optimización de hiperparámetros.
  n_estimators: [50, 100, 200]
  max_depth: [10, 20, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  max_features: ["sqrt", "log2"]
  class_weight: ["balanced", null]

cv:  # Configuración de validación cruzada.
  folds: 5  # Número de divisiones.
  scoring: f1_macro  # Métrica para optimización.

optimization:  # Parámetros para búsqueda de hiperparámetros.
  n_iter: 10  # Combinaciones a probar en RandomizedSearchCV.

metrics:  # Métricas a calcular.
  - accuracy
  - f1_macro
  - f1_per_class

_name: model_pycaret  # Identificador único para directorios y archivos.