# Configuración del modelo RandomForestClassifier (model_2).
# Define parámetros por defecto, espacio de búsqueda para optimización,
# validación cruzada y métricas de evaluación.

name: RandomForestClassifier  # Nombre del modelo usado en el pipeline.

params:  # Parámetros por defecto del modelo.
  n_estimators: 300  # Número de árboles.
  max_depth: 30  # Profundidad máxima.
  min_samples_split: 5  # Mínimo de muestras para dividir un nodo.
  min_samples_leaf: 1  # Mínimo de muestras por hoja.
  class_weight: balanced  # Pondera clases según frecuencia.
  random_state: 42  # Semilla para reproducibilidad.

search_space:  # Espacio de búsqueda para optimización de hiperparámetros.
  n_estimators: [200, 400, 800]
  max_depth: [20, 40, 60, null]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 3]
  class_weight: ["balanced", null]

cv:  # Configuración de validación cruzada.
  folds: 5  # Número de divisiones.
  scoring: f1_macro  # Métrica para optimización.

optimization:  # Parámetros para búsqueda de hiperparámetros.
  n_iter: 15  # Combinaciones a probar en RandomizedSearchCV.

metrics:  # Métricas a calcular.
  - accuracy
  - f1_macro
  - f1_per_class

_name: model_2  # Identificador único para directorios y archivos.