# Configuración de preprocesamiento para el pipeline de Credit Scoring.
# Define el target, features, nuevas features, parámetros de división,
# traducciones, reglas de limpieza y codificación.

target: Puntaje_Credito  # Nombre de la columna objetivo para el modelo.

features:  # Lista de features seleccionadas, ajustada a columnas generadas.
  - Edad
  - Salario_Mensual
  - Num_Tarjetas_Credito
  - Tasa_Interes
  - Retraso_Pago
  - Num_Pagos_Retrasados
  - Cambio_Limite_Credito
  - Num_Consultas_Credito
  - Deuda_Pendiente
  - Edad_Historial_Credito
  - Total_Cuota_Mensual
  - Inversion_Mensual
  - Saldo_Mensual
  - Comportamiento_de_Pago_High_spent_Large_value_payments
  - Comportamiento_de_Pago_High_spent_Medium_value_payments
  - Comportamiento_de_Pago_High_spent_Small_value_payments
  - Comportamiento_de_Pago_Low_spent_Large_value_payments
  - Comportamiento_de_Pago_Low_spent_Medium_value_payments
  - Comportamiento_de_Pago_Low_spent_Small_value_payments
  - Mezcla_Crediticia_Bad
  - Mezcla_Crediticia_Good
  - Mezcla_Crediticia_Standard
  - Pago_Minimo_No
  - Pago_Minimo_Yes
  - Ocupacion_Architect
  - Ocupacion_Developer
  - Ocupacion_Doctor
  - Ocupacion_Engineer
  - Ocupacion_Entrepreneur
  - Ocupacion_Journalist
  - Ocupacion_Lawyer
  - Ocupacion_Manager
  - Ocupacion_Mechanic
  - Ocupacion_Media_Manager
  - Ocupacion_Musician
  - Ocupacion_Scientist
  - Ocupacion_Teacher
  - Ocupacion_Writer
  - debt_to_income
  - payment_to_income
  - credit_history_ratio

new_features:  # Nuevas features calculadas.
  - name: debt_to_income
    formula:
      operation: divide
      columns: [Deuda_Pendiente, Salario_Mensual]
  - name: payment_to_income
    formula:
      operation: divide
      columns: [Total_Cuota_Mensual, Salario_Mensual]
  - name: credit_history_ratio
    formula:
      operation: divide
      columns: [Edad_Historial_Credito, Edad]

test_size: 0.2  # Proporción del dataset para prueba.
random_state: 42  # Semilla para reproducibilidad.

translations:  # Traducciones de columnas crudas.
  ID: ID
  Customer_ID: ID_Cliente
  Month: Mes
  Name: Nombre
  Age: Edad
  SSN: Numero_Seguro_Social
  Occupation: Ocupacion
  Annual_Income: Ingreso_Anual
  Monthly_Inhand_Salary: Salario_Mensual
  Num_Bank_Accounts: Num_Cuentas_Bancarias
  Num_Credit_Card: Num_Tarjetas_Credito
  Interest_Rate: Tasa_Interes
  Num_of_Loan: Num_Prestamos
  Type_of_Loan: Tipo_Prestamo
  Delay_from_due_date: Retraso_Pago
  Num_of_Delayed_Payment: Num_Pagos_Retrasados
  Changed_Credit_Limit: Cambio_Limite_Credito
  Num_Credit_Inquiries: Num_Consultas_Credito
  Credit_Mix: Mezcla_Crediticia
  Outstanding_Debt: Deuda_Pendiente
  Credit_Utilization_Ratio: Ratio_Utilizacion_Credito
  Credit_History_Age: Edad_Historial_Credito
  Payment_of_Min_Amount: Pago_Minimo
  Total_EMI_per_month: Total_Cuota_Mensual
  Amount_invested_monthly: Inversion_Mensual
  Payment_Behaviour: Comportamiento_de_Pago
  Monthly_Balance: Saldo_Mensual
  Credit_Score: Puntaje_Credito

cleaning:  # Reglas de limpieza.
  min_age: 18
  max_age_credit_ratio: 1.5
  drop_columns:
    - ID
    - ID_Cliente
    - Mes
    - Ingreso_Anual
    - Ratio_Utilizacion_Credito
    - Num_Cuentas_Bancarias
    - Num_Prestamos
    - Nombre
    - Tipo_Prestamo
    - Numero_Seguro_Social

encoding:  # Reglas de codificación.
  Comportamiento_de_Pago:
    drop: null
  Mezcla_Crediticia:
    drop: null
  Pago_Minimo:
    drop: first
  Ocupacion:
    drop: first

target_classes:  # Clases del target.
  - Poor
  - Standard
  - Good